// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1sTBxD0IQHCUh14bf6YcxfILCblXmRcY',
    appId: '1:367665624069:web:ed0f024fc00c373780186c',
    messagingSenderId: '367665624069',
    projectId: 'attendence-app-5201e',
    authDomain: 'attendence-app-5201e.firebaseapp.com',
    storageBucket: 'attendence-app-5201e.firebasestorage.app',
    measurementId: 'G-H1G4KXPSYV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaDFwPDGiMUDArfADpBBsouU2r5UfOgqI',
    appId: '1:367665624069:android:d7efa0ba4e7f504380186c',
    messagingSenderId: '367665624069',
    projectId: 'attendence-app-5201e',
    storageBucket: 'attendence-app-5201e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJSLeYcdvnxs3G8uBwQK0hDvhSq4Pf4fY',
    appId: '1:367665624069:ios:909cc655ee26ab4f80186c',
    messagingSenderId: '367665624069',
    projectId: 'attendence-app-5201e',
    storageBucket: 'attendence-app-5201e.firebasestorage.app',
    iosBundleId: 'com.example.attendec',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJSLeYcdvnxs3G8uBwQK0hDvhSq4Pf4fY',
    appId: '1:367665624069:ios:909cc655ee26ab4f80186c',
    messagingSenderId: '367665624069',
    projectId: 'attendence-app-5201e',
    storageBucket: 'attendence-app-5201e.firebasestorage.app',
    iosBundleId: 'com.example.attendec',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1sTBxD0IQHCUh14bf6YcxfILCblXmRcY',
    appId: '1:367665624069:web:ce25e130af6c64fc80186c',
    messagingSenderId: '367665624069',
    projectId: 'attendence-app-5201e',
    authDomain: 'attendence-app-5201e.firebaseapp.com',
    storageBucket: 'attendence-app-5201e.firebasestorage.app',
    measurementId: 'G-X5YGR61JFK',
  );
}
